{
    'name': 'Intern Work Management',
    'version': '1.0',
    'depends': ['base', 'project', 'hr', 'calendar', 'mail'],
    'data': [
        'views/evaluation_rubric_views.xml',
        'views/intern_assessment_campaign_views.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/cron.xml',
        'views/dashboard_views.xml',
        'views/daily_report_views.xml',
        'views/weekly_report_views.xml',
        'views/task_presentation_views.xml',
        'views/menu_views.xml',
        'views/project_views.xml',
    ],
    'installable': True,
    'application': True,
}
